//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sparepart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class badetail
    {
        public int BAID { get; set; }
        public int SeqBAID { get; set; }
        public string KodeBarangTipe { get; set; }
        public int SatuanID { get; set; }
        public int Qty { get; set; }
    
        public virtual baheader baheader { get; set; }
        public virtual masterbarang masterbarang { get; set; }
        public virtual mastersatuan mastersatuan { get; set; }
    }
}
