//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sparepart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bkbdetail
    {
        public int SeqBKBID { get; set; }
        public int BKBID { get; set; }
        public int BAID { get; set; }
        public int SeqBAID { get; set; }
        public string Keterangan { get; set; }
    
        public virtual baheader baheader { get; set; }
    }
}
