//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sparepart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bkbheader
    {
        public int BKBID { get; set; }
        public int BAID { get; set; }
        public string UserInput { get; set; }
        public System.DateTime TanggalInput { get; set; }
        public string UserUpdate { get; set; }
        public System.DateTime TanggalUpdate { get; set; }
        public string Approval { get; set; }
    
        public virtual baheader baheader { get; set; }
    }
}
