//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sparepart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class btbmutasidetail
    {
        public int SeqBTBID { get; set; }
        public int BTBID { get; set; }
        public int SJID { get; set; }
        public int SeqSJID { get; set; }
    
        public virtual sjheader sjheader { get; set; }
    }
}
