//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sparepart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class btbsupplierdetail
    {
        public int SeqBTBID { get; set; }
        public int BTBID { get; set; }
        public string KodeBarangTipe { get; set; }
        public int CabangID { get; set; }
    
        public virtual btbsupplierheader btbsupplierheader { get; set; }
        public virtual mastercabang mastercabang { get; set; }
        public virtual masterbarang masterbarang { get; set; }
    }
}
