//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sparepart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class btbsupplierheader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public btbsupplierheader()
        {
            this.btbsupplierdetails = new HashSet<btbsupplierdetail>();
        }
    
        public int BTBID { get; set; }
        public string KodeBTBeProc { get; set; }
        public string UserInput { get; set; }
        public System.DateTime TanggalInput { get; set; }
        public string UserUpdate { get; set; }
        public System.DateTime TanggalUpdate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<btbsupplierdetail> btbsupplierdetails { get; set; }
    }
}
