//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sparepart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fpsheader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public fpsheader()
        {
            this.fpsdetails = new HashSet<fpsdetail>();
        }
    
        public int FPSID { get; set; }
        public string UserID { get; set; }
        public Nullable<int> TokoID { get; set; }
        public Nullable<int> CabangID { get; set; }
        public Nullable<int> UnitID { get; set; }
        public string NoTicket { get; set; }
        public string Approval { get; set; }
        public string JenisFPS { get; set; }
        public string NamaPemohon { get; set; }
        public string NIKPemohon { get; set; }
        public string UserInput { get; set; }
        public Nullable<System.DateTime> TanggalInput { get; set; }
        public string UserUpdate { get; set; }
        public Nullable<System.DateTime> TanggalUpdate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fpsdetail> fpsdetails { get; set; }
        public virtual mastercabang mastercabang { get; set; }
        public virtual mastertoko mastertoko { get; set; }
        public virtual masterunit masterunit { get; set; }
        public virtual masteruser masteruser { get; set; }
    }
}
