//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sparepart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventorytransaction
    {
        public int TransactionID { get; set; }
        public Nullable<int> CabangID { get; set; }
        public Nullable<int> JenisID { get; set; }
        public string KodeBarangTipe { get; set; }
        public Nullable<int> SaldoIN { get; set; }
        public Nullable<int> SaldoOUT { get; set; }
        public Nullable<decimal> Harga { get; set; }
        public Nullable<System.DateTime> TanggalTransaksi { get; set; }
        public string UserInput { get; set; }
    
        public virtual inventory inventory { get; set; }
    }
}
