//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sparepart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public inventory()
        {
            this.inventorytransactions = new HashSet<inventorytransaction>();
        }
    
        public string KodeBarangTipe { get; set; }
        public int CabangID { get; set; }
        public int JenisID { get; set; }
        public int Stock { get; set; }
        public decimal ACost { get; set; }
    
        public virtual mastercabang mastercabang { get; set; }
        public virtual jeni jeni { get; set; }
        public virtual masterbarang masterbarang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inventorytransaction> inventorytransactions { get; set; }
    }
}
