//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sparepart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sjheader
    {
        public int SJID { get; set; }
        public Nullable<int> FPSID { get; set; }
        public Nullable<int> CabangID { get; set; }
        public string Keterangan { get; set; }
        public Nullable<sbyte> JenisSJ { get; set; }
        public string UserInput { get; set; }
        public Nullable<System.DateTime> TanggalInput { get; set; }
        public string UserUpdate { get; set; }
        public Nullable<System.DateTime> TanggalUpdate { get; set; }
    }
}
