//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sparepart.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbsparepartEntities : DbContext
    {
        public dbsparepartEntities()
            : base("name=dbsparepartEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<aks> akses { get; set; }
        public virtual DbSet<badetail> badetails { get; set; }
        public virtual DbSet<baheader> baheaders { get; set; }
        public virtual DbSet<bkbdetail> bkbdetails { get; set; }
        public virtual DbSet<bkbheader> bkbheaders { get; set; }
        public virtual DbSet<btbmutasidetail> btbmutasidetails { get; set; }
        public virtual DbSet<btbmutasiheader> btbmutasiheaders { get; set; }
        public virtual DbSet<btbsupplierdetail> btbsupplierdetails { get; set; }
        public virtual DbSet<btbsupplierheader> btbsupplierheaders { get; set; }
        public virtual DbSet<fpsdetail> fpsdetails { get; set; }
        public virtual DbSet<fpsheader> fpsheaders { get; set; }
        public virtual DbSet<hakaks> hakakses { get; set; }
        public virtual DbSet<inventory> inventories { get; set; }
        public virtual DbSet<inventorytransaction> inventorytransactions { get; set; }
        public virtual DbSet<jeni> jenis { get; set; }
        public virtual DbSet<masterbarang> masterbarangs { get; set; }
        public virtual DbSet<mastercabang> mastercabangs { get; set; }
        public virtual DbSet<masterkategori> masterkategoris { get; set; }
        public virtual DbSet<masterrole> masterroles { get; set; }
        public virtual DbSet<mastersatuan> mastersatuans { get; set; }
        public virtual DbSet<mastertoko> mastertokoes { get; set; }
        public virtual DbSet<masterunit> masterunits { get; set; }
        public virtual DbSet<masteruser> masterusers { get; set; }
        public virtual DbSet<sjdetail> sjdetails { get; set; }
        public virtual DbSet<sjheader> sjheaders { get; set; }
    }
}
